version: '3.4'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8008:9000"
    restart: always
    privileged: true
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: always
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    restart: always
volumes:
  portainer_data:

